# Generated by Django 4.2.3 on 2024-02-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_completedorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CompletedOrder',
        ),
    ]
